{
  esbuild,
  fetchurl,
  lib,
  stdenv,
}:

let
  sipJs = fetchurl {
    url = "https://registry.npmjs.org/sip.js/-/sip.js-0.21.2.tgz";
    hash = "sha256-q783S8z1D90PZZ4k3XCoOgutCVU70W+ktslAIQU/Zss=";
  };
in
stdenv.mkDerivation {
  pname = "pbx-webphone";
  version = "0.1.0";

  src = ./assets;

  nativeBuildInputs = [ esbuild ];

  buildPhase = ''
    runHook preBuild

    mkdir -p work
    tar -xzf ${sipJs} -C work

    # Bundle the library into a classic browser global (no bundler/CDN at runtime).
    esbuild work/package/lib/index.js \
      --bundle \
      --minify \
      --format=iife \
      --global-name=SIP \
      --outfile=sip.min.js

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/share/webphone
    cp ./*.html ./*.css ./*.js ./*.svg $out/share/webphone/
    cp work/package/LICENSE.md $out/share/webphone/sip.min.js.LEGAL.txt

    runHook postInstall
  '';

  # config.js is generated by the NixOS module (it depends on runtime settings)
  # and is served by nginx separately, so it is intentionally absent here.

  meta = {
    description = "Static SIP.js WebRTC softphone served by the telephony stack";
    license = lib.licenses.mit;
    platforms = lib.platforms.linux;
  };
}
